locals {
  site_name     = "Transfer AWS SFTP [User: ${aws_transfer_user.transfer_user.user_name}]"
  remote_dir    = "/uploads"
  comment       = "Generated by Terraform"
  encoding_type = "Auto"
  sftp_port     = 22

  filezilla_site_config = <<EOT
<?xml version="1.0" encoding="UTF-8"?>
<FileZilla3 version="3.68.1" platform="mac">
  <Servers>
    <Server>
      <Host>${aws_transfer_server.transfer_server.endpoint}</Host>
      <Port>${local.sftp_port}</Port>
      <User>${aws_transfer_user.transfer_user.user_name}</User>
      <Keyfile>${local.s3_file_id_rsa}</Keyfile>
      <EncodingType>${local.encoding_type}</EncodingType>
      <Name>${local.site_name}</Name>
      <Comments>${local.comment}</Comments>
      <LocalDir>${aws_transfer_user.transfer_user.home_directory}</LocalDir>
      <RemoteDir>${local.remote_dir}</RemoteDir>
      <Folder>${local.organization_name}</Folder>
      <Protocol>1</Protocol>
      <Type>0</Type>
      <Logontype>5</Logontype>
      <BypassProxy>0</BypassProxy>
      <SyncBrowsing>0</SyncBrowsing>
      <DirectoryComparison>0</DirectoryComparison>
      <TimezoneOffset>0</TimezoneOffset>
      <PasvMode>MODE_DEFAULT</PasvMode>
      <MaximumMultipleConnections>0</MaximumMultipleConnections>
    </Server>
  </Servers>
</FileZilla3>
EOT
}

resource "aws_s3_object" "s3_object_filezilla_config" {
  depends_on = [aws_s3_object.s3_folder]
  bucket     = aws_s3_bucket.s3_bucket.id
  key        = "${local.s3_bucket_path_ftp_connector}/filezilla-site.xml"
  content    = local.filezilla_site_config
}